[package]
name = "cold"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
bench = false
test = false
harness = false

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
mallocator = "0.1.0"
